### PR TITLE
fix: add OwnerReferences to created AnalysisRuns

### LINKED ISSUE #691: AnalysisRun OwnerReference to MonoVertex
**Describe the bug**
We want the AnalysisRun to get deleted when the MonoVertex/Pipeline gets deleted

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by dpadhiar**
Fixes #691 

### Modifications

Fixes issue where we were not adding an OwnerReference to related AnalysisRuns that are created during a Progressive upgrade that uses them.

### Verification

Running progressive upgrades locally on MonoVertexRollout and checking the created AnalysisRun is created with a ownerReference and is deleted when the rollout is.

```
- apiVersion: argoproj.io/v1alpha1
  kind: AnalysisRun
  metadata:
    creationTimestamp: "2025-04-07T23:59:28Z"
    generation: 2
    labels:
      app.kubernetes.io/part-of: numaplane
    name: my-monovertex-1
    namespace: example-namespace
    ownerReferences:
    - apiVersion: numaflow.numaproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: MonoVertex
      name: my-monovertex-1
      uid: 1cf0d96d-0cda-4fd7-890c-30ff3caf2f55
    resourceVersion: "890142"
    uid: 8ed46273-5310-4cee-922e-415e10909d8f
```

### Backward incompatibilities

n/a

### CODE REVIEW

**Review by juliev0 — CHANGES_REQUESTED** [review]
it needs to be owned by the MonoVertex/Pipeline, not the rollout. Otherwise, we would be accumulating these forever until the rollout gets deleted.

**Comment by dpadhiar** [comment]
> it needs to be owned by the MonoVertex/Pipeline, not the rollout. Otherwise, we would be accumulating these forever until the rollout gets deleted.

Ack, just changed that now. Will do a quick test.

**Comment by dpadhiar** [comment]
> > it needs to be owned by the MonoVertex/Pipeline, not the rollout. Otherwise, we would be accumulating these forever until the rollout gets deleted.
> 
> Ack, just changed that now. Will do a quick test.

Quickly tested, new analysisrun was created and previous was deleted after two successive progressive upgrades. Changing PR back to ready to review.

File: internal/controller/progressive/analysis.go [hunk 1]
```diff
@@ -123,6 +124,8 @@ func CreateAnalysisRun(ctx context.Context, analysis apiv1.Analysis, existingUpg
 		return err
 	}
 
+	// set ownerReference to guarantee AnalysisRun deletion when rollout is cleaned up
```
Comment (juliev0) [inline internal/controller/progressive/analysis.go:127]:
```suggestion
	// set ownerReference to guarantee AnalysisRun deletion when owner is cleaned up
```

File: internal/controller/progressive/analysis.go [hunk 2]
```diff
@@ -95,7 +96,7 @@ Parameters:
 Returns:
   - An error if any issues occur during processing.
 */
-func CreateAnalysisRun(ctx context.Context, analysis apiv1.Analysis, existingUpgradingChildDef *unstructured.Unstructured, client client.Client) error {
+func CreateAnalysisRun(ctx context.Context, analysis apiv1.Analysis, existingUpgradingChildDef *unstructured.Unstructured, ownerReference metav1.OwnerReference, client client.Client) error {
```
Comment (juliev0) [inline internal/controller/progressive/analysis.go:99]: need to update the parameters described above to include the new one

**Review by juliev0 — APPROVED** [review]
