### PR TITLE
fix: various bugs related to progressive rollout

### LINKED ISSUE #550: race condition on pipeline/isbsvc blue/green deletion
**Describe the bug**
A successful blue/green Pipeline can be marked "recyclable" and then deleted, but ISBService `AssessUpgradingChild()` seems to look for the Pipeline child. Seems like it may still be performing its assessment after the Pipeline gets deleted?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #550 

### Modifications

This fixes a few issues (all of them are described inline):
- Reset the entire Upgrading Child Status and Promoted Child Status instead of just setting the inner structs that are common to all Rollouts
- Make sure to reset the Promoted Child Set if there's a new promoted child (it didn't look like we were)
- Make sure the Assessment of ISBService isn't dependent on the Pipeline still being there (it could be deleted)
- Premature success was being declared if it succeeded just once within the time window
- copy/paste error
- functional test bug for progressive case

### Verification

Ran e2e test many times, all passing.

**Manual testing:**
For **MonoVertex**, I did a test in which I:
1. Create MonoVertexRollout with scale.min/max=3,6
2. Update image to a bad one
3. Observe initial MonoVertex scale down to 1 Pod
4. Observe NextAssessmentTime gets set, then AssessUntil after the first assessment is made
5. Observe it's marked Failed as soon as the first failure is recorded
6. Observed promoted MonoVertex gets scaled back up
7. Restore MonoVertexRollout back to original image 
8. Observe same steps as above happen except that determination of "Success" happens only once "AssessUntil" time is reached

For **InterstepBufferService** and **Pipeline**, I did a test in which I:
1. Create ISBServiceRollout and PipelineRollout
2. Update ISBServiceRollout to a different version
3. Observe initial Pipeline scale down
4. Observe that Successful assessment is only made for each after the AssessUntil time is reached
5. Observe new pipeline and new isbservice get promoted

### Backward incompatibilities

None

### CODE REVIEW

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 1]
```diff
@@ -418,13 +418,16 @@ func (r *ISBServiceRolloutReconciler) processExistingISBService(ctx context.Cont
...
-		// Get the ISBServiceRollout live resource
+		// Get the ISBServiceRollout live resource so we can grab the ProgressiveStatus from that for our own local isbServiceRollout
+		// (Note we don't copy the entire Status in case we've updated something locally)
 		liveISBServiceRollout, err := kubernetes.NumaplaneClient.NumaplaneV1alpha1().ISBServiceRollouts(isbServiceRollout.Namespace).Get(ctx, isbServiceRollout.Name, metav1.GetOptions{})
 		if err != nil {
 			return 0, fmt.Errorf("error getting the live ISBServiceRollout for assessment processing: %w", err)
 		}
 
-		done, _, progressiveRequeueDelay, err := progressive.ProcessResource(ctx, isbServiceRollout, liveISBServiceRollout, existingISBServiceDef, isbServiceNeedsToUpdate, r, r.client)
+		isbServiceRollout.Status.ProgressiveStatus = *liveISBServiceRollout.Status.ProgressiveStatus.DeepCopy()
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:428]: just copy the ProgressiveStatus from the live resource here so that in the progressive code, we can just one have one single version of our rollout object

File: internal/controller/isbservicerollout/isbservicerollout_progressive.go [hunk 2]
```diff
@@ -59,58 +58,27 @@ func (r *ISBServiceRolloutReconciler) AssessUpgradingChild(ctx context.Context,
...
-				foundPipeline = true
-				break
-			}
-		}
-		if !foundPipeline {
-			numaLogger.Debugf("Can't assess isbsvc; didn't find a Pipeline associated with PipelineRollout %s/%s using this isbsvc",
-				pipelineRollout.GetNamespace(), pipelineRollout.GetName())
+		upgradingPipelineStatus := pipelineRollout.Status.ProgressiveStatus.UpgradingPipelineStatus
+		if upgradingPipelineStatus == nil || upgradingPipelineStatus.InterStepBufferServiceName != existingUpgradingChildDef.GetName() {
+			numaLogger.WithValues("pipelinerollout", pipelineRollout.GetName()).Debug("can't assess ISBService; pipeline is not yet upgrading with this ISBService")
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_progressive.go:66]: previously we looked for the `Pipeline` itself to determine if it's using this isbsvc. This was a problem, because the Pipeline could have already been deleted. Now we use the `PipelineRollout.ProgressiveStatus.UpgradingChildStatus.InterstepBufferServiceName` to confirm that the upgrading Pipeline that we're getting an AssessmentResult from is in fact using this isbsvc

File: internal/controller/isbservicerollout/isbservicerollout_progressive.go [hunk 3]
```diff
@@ -123,7 +91,7 @@ func (r *ISBServiceRolloutReconciler) ProcessPromotedChildPreUpgrade(
 	return false, nil
 }
 
-func (r *ISBServiceRolloutReconciler) ProcessPromotedChildPostUpgrade(
+func (r *ISBServiceRolloutReconciler) ProcessPromotedChildPostFailure(
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_progressive.go:94]: I thought maybe this was a more accurate name for this case, since it's only the failure case and not the success case

File: internal/controller/progressive/progressive.go [hunk 4]
```diff
@@ -99,10 +104,12 @@ func ProcessResource(
...
-			if liveRolloutObject.GetPromotedChildStatus() == nil {
-				rolloutObject.SetPromotedChildStatus(&apiv1.PromotedChildStatus{Name: existingPromotedChild.GetName()})
-			} else {
-				rolloutObject.SetPromotedChildStatus(liveRolloutObject.GetPromotedChildStatus().DeepCopy())
+			promotedChildStatus := rolloutObject.GetPromotedChildStatus()
+			if promotedChildStatus == nil || promotedChildStatus.Name != existingPromotedChild.GetName() {
+				err = rolloutObject.ResetPromotedChildStatus(existingPromotedChild)
+				if err != nil {
+					return false, false, 0, err
+				}
```
Comment (juliev0) [inline internal/controller/progressive/progressive.go:112]: I figure we need to also Reset this in the case that the promoted child name has changed from before

Comment (juliev0) [reply internal/controller/progressive/progressive.go:112]: Also, by calling `ResetPromotedChildStatus()`, we now reset the entire encapsulating promoted child struct for that particular Rollout.

File: internal/controller/progressive/progressive.go [hunk 5]
```diff
@@ -274,12 +279,6 @@ func processUpgradingChild(
 
 		// if so, mark the existing one for garbage collection and then create a new upgrading one
 		if needsUpdating {
-			if liveRolloutObject.GetPromotedChildStatus() == nil {
-				rolloutObject.SetPromotedChildStatus(&apiv1.PromotedChildStatus{Name: existingPromotedChildDef.GetName()})
-			} else {
-				rolloutObject.SetPromotedChildStatus(liveRolloutObject.GetPromotedChildStatus().DeepCopy())
-			}
```
Comment (juliev0) [inline internal/controller/progressive/progressive.go:281]: I relocated the setting of Promoted Child Status to the beginning of the `progressive.ProcessResource()` call - we should have the same promoted child throughout (up until the end of the Success case at least)

File: internal/controller/progressive/progressive.go [hunk 6]
```diff
@@ -85,6 +90,15 @@ func ProcessResource(
...
 	numaLogger := logger.FromContext(ctx)
 
+	// Make sure that our Promoted Child Status reflects the current promoted child
+	promotedChildStatus := rolloutObject.GetPromotedChildStatus()
+	if promotedChildStatus == nil || promotedChildStatus.Name != existingPromotedChild.GetName() {
+		err := rolloutObject.ResetPromotedChildStatus(existingPromotedChild)
+		if err != nil {
+			return false, false, 0, err
+		}
+	}
```
Comment (juliev0) [inline internal/controller/progressive/progressive.go:100]: I think we can just call this once at the beginning if either the PromotedChildStatus is nil or if there's a new promoted child. 

By calling `ResetPromotedChildStatus()`, we can update the [InterstepBufferServiceName](https://github.com/numaproj/numaplane/blob/pipeline-ref-to-isbsvc/pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go#L69) for UpgradingPipelineStatus

File: pkg/apis/numaplane/v1alpha1/isbservicerollout_types.go [hunk 7]
```diff
@@ -105,8 +106,8 @@ func (isbServiceRollout *ISBServiceRollout) GetRolloutGVK() schema.GroupVersionK
 
 func (isbServiceRollout *ISBServiceRollout) GetChildGVR() metav1.GroupVersionResource {
 	return metav1.GroupVersionResource{
-		Group:    numaflowv1.PipelineGroupVersionKind.Group,
-		Version:  numaflowv1.PipelineGroupVersionKind.Version,
+		Group:    numaflowv1.ISBGroupVersionKind.Group,
+		Version:  numaflowv1.ISBGroupVersionKind.Version,
```
Comment (juliev0) [inline pkg/apis/numaplane/v1alpha1/isbservicerollout_types.go:110]: this was a copy/paste error

File: tests/e2e/functional-e2e/functional_test.go [hunk 8]
```diff
@@ -303,7 +303,9 @@ var _ = Describe("Functional e2e", Serial, func() {
 		Document("setting desiredPhase=Paused")
 		currentMonoVertexSpec.Lifecycle.DesiredPhase = numaflowv1.MonoVertexPhasePaused
 
-		UpdateMonoVertexRollout(monoVertexRolloutName, currentMonoVertexSpec, numaflowv1.MonoVertexPhasePaused)
+		UpdateMonoVertexRollout(monoVertexRolloutName, currentMonoVertexSpec, numaflowv1.MonoVertexPhasePaused, func(spec numaflowv1.MonoVertexSpec) bool {
+			return spec.Lifecycle.DesiredPhase == numaflowv1.MonoVertexPhasePaused
+		})
```
Comment (juliev0) [inline tests/e2e/functional-e2e/functional_test.go:308]: this fixes the unit test (described below)

File: tests/e2e/monovertex.go [hunk 9]
```diff
@@ -362,8 +362,11 @@ func UpdateMonoVertexRollout(name string, newSpec numaflowv1.MonoVertexSpec, exp
 		rollout.Spec.MonoVertex.Spec.Raw = rawSpec
 		return rollout, nil
 	})
+	Document("Verifying MonoVertex spec got updated")
+	// get Pipeline to check that spec has been updated to correct spec
+	VerifyMonoVertexSpec(Namespace, name, verifySpecFunc)
```
Comment (juliev0) [inline tests/e2e/monovertex.go:367]: this fixes the unit test - before we weren't waiting for the spec to get updated, which means that we could start verifying the previous "promoted" MonoVertex for various checks, rather than verifying the new one we're updating

File: tests/e2e/pipeline.go [hunk 10]
```diff
@@ -516,7 +516,7 @@ func UpdatePipelineRollout(name string, newSpec numaflowv1.PipelineSpec, expecte
 	}
 
 	// rollout phase will be pending if we are expecting a long pausing state and Pipeline will not be fully updated
-	if expectedFinalPhase != numaflowv1.PipelinePhasePausing {
+	if !(UpgradeStrategy == config.PPNDStrategyID && expectedFinalPhase == numaflowv1.PipelinePhasePausing) {
```
Comment (juliev0) [inline tests/e2e/pipeline.go:519]: this is a clarification that this check is really intended for PPND

File: internal/controller/progressive/progressive.go [hunk 11]
```diff
@@ -322,26 +318,31 @@ func processUpgradingChild(
...
 
 	case apiv1.AssessmentResultSuccess:
-		// Label the new child as promoted and then remove the label from the old one
-		numaLogger.WithValues("old child", existingPromotedChildDef.GetName(), "new child", existingUpgradingChildDef.GetName(), "replacing 'promoted' child")
-		reasonSuccess := common.LabelValueProgressiveSuccess
-		err := ctlrcommon.UpdateUpgradeState(ctx, c, common.LabelValueUpgradePromoted, &reasonSuccess, existingUpgradingChildDef)
-		if err != nil {
-			return false, false, 0, err
-		}
+		if childStatus.CanDeclareSuccess() {
```
Comment (juliev0) [inline internal/controller/progressive/progressive.go:321]: I'm looking for `>=AssessUntil` here. Now the call to `CanAssess()` above only looks for whether it's reached the `NextAssessmentTime` (and whether it's previously failed). 

So, basically:
- if we haven't reached `NextAssessmentTime`, we don't assess
- Once we reach `NextAssessmentTime`, we can start assessing. If we see a failure, we can mark it and stop assessing.
- Once we reach `AssessUntil`, we can declare success if we never saw a failure.

File: internal/controller/monovertexrollout/monovertexrollout_progressive.go [hunk 12]
```diff
@@ -209,6 +209,8 @@ func scaleDownMonoVertex(
 	// If for the vertex we already set a Scaled scale value, we only need to update the actual pods count
 	// to later verify that the pods were actually scaled down.
 	// We want to skip scaling down again.
+	// TODO: why do we concern ourselves if vertexScaleValues.ScaleTo != 0? If we scale 1 Pod to 0, we go past here even if the scale values
+	// were found
```
Comment (juliev0) [inline internal/controller/monovertexrollout/monovertexrollout_progressive.go:213]: need more info from @afugazzotto on this

File: internal/controller/progressive/progressive.go (hunk 6 above)
Comment (juliev0) [reply internal/controller/progressive/progressive.go:100]: With this, we basically reset the Promoted status whenever there's a new promoted child that starts the upgrading process.

File: internal/controller/progressive/progressive.go [hunk 13]
```diff
@@ -322,26 +318,31 @@ func processUpgradingChild(
...
+			rolloutObject.GetRolloutStatus().MarkProgressiveUpgradeSucceeded(fmt.Sprintf("New Child Object %s/%s Running", existingUpgradingChildDef.GetNamespace(), existingUpgradingChildDef.GetName()), rolloutObject.GetRolloutObjectMeta().Generation)
+			childStatus.AssessmentResult = apiv1.AssessmentResultSuccess
+			rolloutObject.SetUpgradingChildStatus(childStatus)
+			rolloutObject.GetRolloutStatus().MarkDeployed(rolloutObject.GetRolloutObjectMeta().Generation)
+
+			// we're done
+			return true, false, assessmentInterval, nil
+		} else {
+			return false, false, assessmentInterval, nil
+		}
```
Comment (juliev0) [inline internal/controller/progressive/progressive.go:345]: only these lines changed I believe. Now, we can always return true if we've reached the end of the time window

File: tests/e2e/common.go [hunk 14]
```diff
@@ -44,9 +44,7 @@ var (
 	dynamicClient       dynamic.DynamicClient
 	testEnv             *envtest.Environment
 	ctx                 context.Context
-	cancel              context.CancelFunc
-	suiteTimeout        = 35 * time.Minute // Note: if we start seeing "client rate limiter: context deadline exceeded", we need to increase this value
```
Comment (juliev0) [inline tests/e2e/common.go:48]: I removed `suiteTimeout` and the timeout that was in Github Actions for the e2e test. Now there's just the one timeout in the Makefile target for `go test` itself. I think that should be sufficient.

File: internal/controller/progressive/progressive.go [hunk 15]
```diff
@@ -322,26 +318,31 @@ func processUpgradingChild(
...
-			return false, false, 0, err
-		}
+		if childStatus.CanDeclareSuccess() {
 
-		err = ctlrcommon.UpdateUpgradeState(ctx, c, common.LabelValueUpgradeRecyclable, &reasonSuccess, existingPromotedChildDef)
-		if err != nil {
-			return false, false, 0, err
-		}
+			// Label the new child as promoted and then remove the label from the old one
+			numaLogger.WithValues("old child", existingPromotedChildDef.GetName(), "new child", existingUpgradingChildDef.GetName(), "replacing 'promoted' child")
```
Comment (afugazzotto) [inline internal/controller/progressive/progressive.go:324]: You may want to log the message using Debug or other level.

File: internal/controller/pipelinerollout/pipelinerollout_progressive.go [hunk 16]
```diff
@@ -132,7 +132,7 @@ func (r *PipelineRolloutReconciler) ProcessPromotedChildPreUpgrade(
 }
 
 /*
-ProcessPromotedChildPostUpgrade handles the post-upgrade processing of a promoted pipeline.
+ProcessPromotedChildPostFailure handles the post-upgrade processing of a promoted pipeline.
```
[the remark this answers is not in the document]
Comment (juliev0) [reply internal/controller/pipelinerollout/pipelinerollout_progressive.go:135]: good catch

**Comment by juliev0** [comment]
@afugazzotto I made the changes based on your comments

**Review by afugazzotto — APPROVED** [review]
