### PR TITLE
Phases

### LINKED ISSUE #103: Set Rollout Status Phase Failed on reconciliation errors
# Summary

Update the rollout status with Phase Failed in case of reconciliation errors. Do this on all 3 rollout controllers.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by afugazzotto**
Fixes #103 

### Modifications

- Updated controllers to include setting the status phase as Failed in case of reconciliation errors.
- Created reusable functions for: resource status update, struct-to-struct conversion, GroupVersionResource computation.
- Added ObservedGeneration on status when updating phase.

### Verification

Added some extra unit tests. Done manual tests to check ObservedGeneration and Phase. Unable to test failure cases.

### CODE REVIEW

**Comment by juliev0** [comment]
This isn't related to this PR, but I believe the way we're doing our "ChildResourceDeployed" Condition could potentially use some adjustment (in a future PR). Right now the timestamp of the "ChildResourceDeployed" Condition doesn't really reflect when it was deployed, right? I'm thinking it should.

File: internal/util/util.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+		return err
+	}
+
+	err = json.Unmarshal(jsonBytes, dest)
+	if err != nil {
+		return err
+	}
+
+	return nil
+}
```
Comment (juliev0) [inline internal/util/util.go:17]: nice

**Review by juliev0 — APPROVED** [review]
