### PR TITLE
fix: slow-to-pause pipeline in e2e test needs "pauseGracePeriodSeconds" configured

### LINKED ISSUE #526: flakey e2e test - "Verifying that Pipeline keeps trying to pause"
**Describe the bug**
e2e test which tests the "allow-data-loss" annotation didn't keep trying to pause. 
Link: https://github.com/numaproj/numaplane/actions/runs/13004082300/job/36267856544?pr=525

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #526 

### Modifications

There is an e2e test which tries to pause a pipeline which is very slow to pause. However, I realized that since I wasn't setting `pauseGracePeriodSeconds` in the Pipeline, it was by default getting set to "30 seconds", which meant that it would automatically stop pausing after 30 seconds by Numaflow Controller anyway. Reset to 3600 seconds.

### Verification

e2e

### Backward incompatibilities

N/A

### CODE REVIEW

File: tests/e2e/functional_test.go [hunk 1]
```diff
@@ -378,8 +378,10 @@ var _ = Describe("Functional e2e", Serial, func() {
 
 			document("Creating a slow pipeline")
 			slowPipelineSpec := updatedPipelineSpec.DeepCopy()
-			highRPU := int64(10000)
+			highRPU := int64(10000000)
```
Comment (juliev0) [inline tests/e2e/functional_test.go:381]: at first I was trying to just increase this before I realized the real issue was the pauseGracePeriodSeconds. But I just left this value here since it doesn't harm anything.

**Review by dpadhiar — APPROVED** [review]
LGTM!
