### PR TITLE
fix: return error when a pipeline with the same name already exist without a pipeline Rollout manage it

### LINKED ISSUE #252: Return reconciliation error when a pipeline with the same name already exist without a corresponding rollout
# Summary

Currently, we swallowed the error and directly update the phase in the status when a pipeline with the same name already exist without a pipeline Rollout manage it. We should instead return the error as reconciliation failure so the error is recorded by the metrics via the common error handler.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by xdevxy**
Fixes #252 

### Modifications

This PR returns the reconciliation error when a pipeline with the same name already exist without a pipeline Rollout manage it. So the error is recorded by the metrics via the common error handler.

### Verification

`make test`

### CODE REVIEW

File: internal/controller/pipelinerollout_controller.go [hunk 1]
```diff
@@ -370,8 +370,8 @@ func (r *PipelineRolloutReconciler) reconcile(
 	// Object already exists
 	// if Pipeline is not owned by Rollout, fail and return
 	if !checkOwnerRef(existingPipelineDef.OwnerReferences, pipelineRollout.UID) {
-		pipelineRollout.Status.MarkFailed(fmt.Sprintf("Pipeline %s already exists in namespace", pipelineRollout.Name))
-		return false, nil
+		numaLogger.Debugf("PipelineRollout %s failed because Pipeline %s already exists in namespace", pipelineRollout.Name, existingPipelineDef.Name)
+		return false, fmt.Errorf("pipeline %s already exists in namespace", existingPipelineDef.Name)
```
Comment (juliev0) [inline internal/controller/pipelinerollout_controller.go:374]:
```suggestion
		errStr := fmt.Sprintf("Pipeline %s already exists in namespace, not owned by PipelineRollout", existingPipelineDef.Name)
		numaLogger.Debugf("PipelineRollout %s failed because %s", pipelineRollout.Name, errStr)
		return false, fmt.Error(errStr)
```

**Review by juliev0 — APPROVED** [review]
