### PR TITLE
fix: child resource's labels and annotations are combination of Rollout's specified and existing resource

### LINKED ISSUE #427: Labels and Annotations should be a combination of what's specified in the Rollout and what's in the existing resource
**Describe the bug**
When we make an update to the Labels and Annotations for a pipeline, isbsvc, or monovertex, use the existing resource definition, but also add/replace any keys that are identified in the Rollout.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by dpadhiar**
Fixes #427 

### Modifications

When merging an existing spec with the new spec defined in the parent Rollout, we previously only used the new spec's annotations and labels in the resulting spec. This can cause issues when determining what the appropriate update strategy should be and some labels or annotation can be lost. 

We remedy this by using the `MergeMaps` function to merge the old and new labels and annotations maps without losing any previous keys.

```
func MergeMaps(existing, new map[string]string) map[string]string {
	merged := make(map[string]string)
	if existing != nil {
		merged = existing
	}

	for key, val := range new {
		merged[key] = val
	}

	return merged
}
```

This PR also includes updates to the `ChildNeedsUpdating` functions for the PipelineRollout and MonoVertexRollout reconcilers which also compares the `metadata` of the old and new specs to determine if an update is needed if there is a difference.

### Verification

Created unit test case for MergeMaps function. 

Tested locally with ISBService, Pipeline and MonoVertex rollouts that update from instance 0 to 1 and checking that each child resource has their annotations updated.

### CODE REVIEW

File: internal/controller/common/merge.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+	merged := make(map[string]string)
+	if existing != nil {
+		merged = existing
+	}
+
+	for key, val := range new {
+		merged[key] = val
+	}
+
+	return merged
```
Comment (juliev0) [inline internal/controller/common/merge.go:29]: Great idea!

File: internal/controller/pipelinerollout/pipelinerollout_controller_test.go [hunk 2]
```diff
@@ -659,10 +659,10 @@ func Test_processExistingPipeline_PPND(t *testing.T) {
 			initialInProgressStrategy:      apiv1.UpgradeStrategyPPND,
 			numaflowControllerPauseRequest: &falseValue,
 			isbServicePauseRequest:         &falseValue,
-			expectedInProgressStrategy:     apiv1.UpgradeStrategyNoOp,
+			expectedInProgressStrategy:     apiv1.UpgradeStrategyPPND,
 			expectedRolloutPhase:           apiv1.PhaseDeployed,
 			expectedPipelineSpecResult: func(spec numaflowv1.PipelineSpec) bool {
-				return reflect.DeepEqual(ctlrcommon.PipelineWithDesiredPhase(pipelineSpecWithTopologyChange, numaflowv1.PipelinePhaseRunning), spec)
+				return reflect.DeepEqual(ctlrcommon.PipelineWithDesiredPhase(pipelineSpecWithTopologyChange, numaflowv1.PipelinePhasePaused), spec)
```
Comment (juliev0) [inline internal/controller/pipelinerollout/pipelinerollout_controller_test.go:665]: What's happening here? Previously, it seems that if the spec were already applied, then we would unpause the pipeline and take it out of UpgradeInProgress=PPND. So, what's happening differently now?

Comment (juliev0) [reply internal/controller/pipelinerollout/pipelinerollout_controller_test.go:665]: Can you investigate further? I know this unit test is a little tough since sometimes things take multiple reconciliations in certain cases. But we need to understand what changed that is causing this.

Comment (dpadhiar) [reply internal/controller/pipelinerollout/pipelinerollout_controller_test.go:665]: I think the metadata must need updating if the Pipeline is staying paused.

Comment (dpadhiar) [reply internal/controller/pipelinerollout/pipelinerollout_controller_test.go:665]: > Can you investigate further? I know this unit test is a little tough since sometimes things take multiple reconciliations in certain cases. But we need to understand what changed that is causing this.

can do!

Comment (dpadhiar) [reply internal/controller/pipelinerollout/pipelinerollout_controller_test.go:665]: This is being caused by us checking the annotations and labels in `ChildNeedsUpdating` in the PipelineRollout reconciler. When commenting those checks out, this test case works with the expected values it did before.

I also tried reconciling the rollout multiple times and that did not make the test pass.

**Comment by juliev0** [comment]
moved to "Draft" - please reopen when ready, thanks!

File: internal/controller/pipelinerollout/pipelinerollout_controller_test.go (hunk 2 above)
Comment (dpadhiar) [reply internal/controller/pipelinerollout/pipelinerollout_controller_test.go]: Potentially found and fixed the issue - the existingPipelineDef doesn't have the labels set that are added to Pipeline when they are created with PPND.

Tested this locally by creating PipelineRollout and checking labels of initial Pipeline.

Comment (dpadhiar) [reply internal/controller/pipelinerollout/pipelinerollout_controller_test.go]: Issue was resolved as we found that using `DeepEqual` for maps will not consider nil maps equal to empty maps and thus we created a helper function that checks this first.

File: internal/controller/pipelinerollout/pipelinerollout_controller_test.go [hunk 3]
```diff
@@ -654,7 +654,7 @@ func Test_processExistingPipeline_PPND(t *testing.T) {
 			existingPipelineDef: *ctlrcommon.CreateTestPipelineOfSpec(
 				ctlrcommon.PipelineWithDesiredPhase(pipelineSpecWithTopologyChange, numaflowv1.PipelinePhasePaused),
 				ctlrcommon.DefaultTestPipelineName, numaflowv1.PipelinePhasePaused, numaflowv1.Status{},
-				false, map[string]string{}),
+				false, map[string]string{"numaplane.numaproj.io/isbsvc-name": "my-isbsvc", "numaplane.numaproj.io/parent-rollout-name": "pipelinerollout-test", "numaplane.numaproj.io/upgrade-state": "promoted"}),
```
Comment (juliev0) [inline internal/controller/pipelinerollout/pipelinerollout_controller_test.go:657]: Hate to ask this, but I see we're adding these to `existingPipelineDef` here but not in the other test cases. For consistency, I wonder if we could. You know how most of them are using the function `createDefaultTestPipeline()`? What if we set these same labels in that function?

**Review by juliev0 — APPROVED** [review]
