### PR TITLE
chore: Fix flakey test

### LINKED ISSUE #199: Flakey e2e test - "dataLossPrevention=true" - Numaflow Vertex Pods stuck in Pending state
**Describe the bug**
Happened [here](https://github.com/numaproj/numaplane/actions/runs/10363883081/job/28688264978?pr=192) and [here](https://github.com/numaproj/numaplane/actions/runs/10378855139/job/28735910196)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #199 

### Modifications

1. this fixes the flakey e2e test. Root cause was because the cluster for the e2e test testing "dataLossPrevention=true" wasn't clean, and still had a lingering Job running from the Pipeline of the previous test. Have described the issue that occurs [here](https://github.com/numaproj/numaflow/issues/1956). 
2. Refactored a bit to subdivide the test which was previously in one big long file into multiple files. (would prefer to later maybe move these new files to a `util` subdirectory, and then they could be used by multiple tests)

### Verification

Have run the e2e test 8 times in a row with no failures.

### CODE REVIEW

File: tests/e2e/common.go [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+	ctx           context.Context
+	cancel        context.CancelFunc
+	suiteTimeout  = 5 * time.Minute
+	testTimeout   = 2 * time.Minute
+
+	pipelineRolloutClient           planepkg.PipelineRolloutInterface
+	isbServiceRolloutClient         planepkg.ISBServiceRolloutInterface
+	numaflowControllerRolloutClient planepkg.NumaflowControllerRolloutInterface
+	kubeClient                      clientgo.Interface
+)
```
Comment (juliev0) [inline tests/e2e/common.go:38]: all these variables need to be in a file not including "_test.go" in the name in order to be referenced from the other files

File: .github/workflows/ci.yaml [hunk 2]
```diff
@@ -156,6 +156,15 @@ jobs:
...
 
+      - name: Create second cluster
+        run: |
+          export PATH=$PATH:/usr/local/bin
+          k3d cluster create e2e-data-loss-prevention
+          k3d kubeconfig get e2e-data-loss-prevention > ~/.kube/config
+          echo '127.0.0.1 localhost' | sudo tee -a /etc/hosts
+          echo 'Waiting for the cluster to be ready...'
+          until kubectl cluster-info; do sleep 1; done
+
```
Comment (juliev0) [inline .github/workflows/ci.yaml:167]: this resolves the CI flakey test by creating a clean cluster before the second e2e test runs

**Review by xdevxy — APPROVED** [review]
