### PR TITLE
move code shared between goroutines to a central location in logger

### LINKED ISSUE #89: Race condition found in CI
**Describe the bug**
Race condition during CI Unit tests, logged [here](https://github.com/numaproj/numaplane/actions/runs/9683333594/job/26718520996#step:7:936).

This was "main" at commit https://github.com/numaproj/numaplane/commit/56670923f074e5754b18f6a55a551b357ee72adc 7/26

In case the link becomes unavailable later, it's:
```
WARNING: DATA RACE
Write at 0x00000649d040 by goroutine 343:
  github.com/numaproj/numaplane/internal/util/logger.newNumaLogger()
      /home/runner/work/numaplane/numaplane/internal/util/logger/logger.go:97 +0x45
  github.com/numaproj/numaplane/internal/util/logger.New()
      /home/runner/work/numaplane/numaplane/internal/util/logger/logger.go:89 +0x12d
  github.com/numaproj/numaplane/internal/util/logger.FromContext()
      /home/runner/work/numaplane/numaplane/internal/util/logger/logger.go:141 +0x1c9
  github.com/numaproj/numaplane/internal/controller.(*NumaflowControllerRolloutReconciler).reconcile()
      /home/runner/work/numaplane/numaplane/internal/controller/numaflowcontrollerrollout_controller.go:185 +0xb0
  github.com/numaproj/numaplane/internal/controller.(*NumaflowControllerRolloutReconciler).Reconcile()
      /home/runner/work/numaplane/numaplane/internal/controller/numaflowcontrollerrollout_controller.go:128 +0x4dc
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:[119](https://github.com/numaproj/numaplane/actions/runs/9683333594/job/26718520996#step:7:120) +0x1a1
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:316 +0x58d
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266 +0x350
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227 +0xd5

Previous write at 0x00000649d040 by goroutine 336:
  github.com/numaproj/numaplane/internal/util/logger.newNumaLogger()
      /home/runner/work/numaplane/numaplane/internal/util/logger/logger.go:97 +0x45
  github.com/numaproj/numaplane/internal/util/logger.New()
      /home/runner/work/numaplane/numaplane/internal/util/logger/logger.go:89 +0x12d
  github.com/numaproj/numaplane/internal/util/logger.FromContext()
      /home/runner/work/numaplane/numaplane/internal/util/logger/logger.go:141 +0x1c9
  github.com/numaproj/numaplane/internal/util/kubernetes.ApplyCRSpec()
      /home/runner/work/numaplane/numaplane/internal/util/kubernetes/kubernetes.go:242 +0x6e
  github.com/numaproj/numaplane/internal/controller.(*ISBServiceRolloutReconciler).reconcile()
      /home/runner/work/numaplane/numaplane/internal/controller/isbservicerollout_controller.go:169 +0x750
  github.com/numaproj/numaplane/internal/controller.(*ISBServiceRolloutReconciler).Reconcile()
      /home/runner/work/numaplane/numaplane/internal/controller/isbservicerollout_controller.go:99 +0x4e4
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:119 +0x1a1
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:316 +0x58d
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266 +0x350
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227 +0xd5

Goroutine 343 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:223 +0x7f9
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:234 +0x2c4
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/manager/runnable_group.go:223 +0x1ce
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/manager/runnable_group.go:226 +0x41

Goroutine 336 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:223 +0x7f9
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:234 +0x2c4
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/manager/runnable_group.go:223 +0x1ce
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/manager/runnable_group.go:226 +0x41

```

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #89 

### Modifications

Moved code which shares globals to a place that would only be called once on startup.

### Verification

Ran code, temporarily added a print statement to make sure it did the right thing

### CODE REVIEW

File: internal/util/logger/logger.go [hunk 1]
```diff
@@ -73,6 +73,18 @@ type LogSink struct {
 	depth int
 }
 
+func init() {
+	// Global-level definitions for zerolog
+	zerolog.MessageFieldName = messageFieldName
+	zerolog.TimestampFieldName = timestampFieldName
+	zerolog.TimeFieldFormat = time.RFC3339Nano
+	zerolog.CallerMarshalFunc = zerologCallerMarshalFunc
+	zerolog.LevelFieldMarshalFunc = zerologLevelFieldMarshalFunc
```
Comment (juliev0) [inline internal/util/logger/logger.go:82]: above are all set to either constants or functions

File: internal/util/logger/logger.go [hunk 2]
```diff
@@ -73,6 +73,18 @@ type LogSink struct {
...
+
+	// Set zerolog global level to the most verbose level
+	zerolog.SetGlobalLevel(getZerologLevelFromLogrVerbosity(VerboseLevel))
```
Comment (juliev0) [inline internal/util/logger/logger.go:85]: Confirmed that `getZerologLevelFromLogrVerbosity()` just uses the global `logrVerbosityToZerologLevelMap` which is defined prior to this `Init` function executing according to Golang order of initialization (`var`s defined before `Init` called)

**Review by afugazzotto — APPROVED** [review]

**Review by xdevxy — APPROVED** [review]
