### PR TITLE
fix: e2e testing to accompany fix to progressive condition reset

### LINKED ISSUE #810: Child is deemed to be failed following rollback to previous image
**Describe the bug**

I realized after updating my MVRollout to the successful image, following a Progressive failure, it still marked the Status as "Failed", and so it's still showing up as "Degraded" in ArgoCD:

```
apiVersion: numaplane.numaproj.io/v1alpha1
kind: MonoVertexRollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"numaplane.numaproj.io/v1alpha1","kind":"MonoVertexRollout","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"oss-analytics-numaplanetest1-qal-usw2-55257"},"name":"numaplane-test-mvtx","namespace":"oss-analytics-numaplanetest1-qal"},"spec":{"monoVertex":{"spec":{"scale":{"max":7,"min":3},"sink":{"udsink":{"container":{"image":"docker.intuit.com/quay-rmt/numaio/numaflow-go/sink-log-failure:stable"}}},"source":{"udsource":{"container":{"image":"docker.intuit.com/quay-rmt/numaio/numaflow-go/source-simple-source:stable"}}}}},"strategy":{"analysis":{"args":null,"templates":[{"clusterScope":false,"templateName":"mvtx-acknowledged-messages"}]},"progressive":null}}}
  creationTimestamp: '2025-04-29T20:00:52Z'
  generation: 49
  labels:
    app.kubernetes.io/instance: oss-analytics-numaplanetest1-qal-usw2-55257
  name: numaplane-test-mvtx
  namespace: oss-analytics-numaplanetest1-qal
  resourceVersion: '5772328255'
  uid: 83aef9c3-ef20-4d12-8a6a-4066b5c912a8
spec:
  monoVertex:
    spec:
      scale:
        max: 7
        min: 3
      sink:
        udsink:
          container:
            image: docker.intuit.com/quay-rmt/numaio/numaflow-go/sink-log:stable
      source:
        udsource:
          container:
            image: >-
              docker.intuit.com/quay-rmt/numaio/numaflow-go/source-simple-source:stable
  strategy:
    analysis:
      templates:
        - clusterScope: false
          templateName: mvtx-acknowledged-messages
status:
  conditions:
    - lastTransitionTime: '2025-04-29T20:00:52Z'
      message: Successful
      observedGeneration: 49
      reason: Successful
      status: 'True'
      type: ChildResourceDeployed
    - lastTransitionTime: '2025-07-04T23:17:22Z'
      message: Successful
      observedGeneration: 49
      reason: Successful
      status: 'True'
      type: ChildResourcesHealthy
    - lastTransitionTime: '2025-04-29T20:00:52Z'
      message: MonoVertex unpaused
      observedGeneration: 49
      reason: Unpaused
      status: 'False'
      type: MonoVertexPausingOrPaused
    - lastTransitionTime: '2025-07-04T23:17:16Z'
      message: >-
        New Child Object oss-analytics-numaplanetest1-qal/numaplane-test-mvtx-40
        Failed
      observedGeneration: 48
      reason: Failed
      status: 'False'
      type: ProgressiveUpgradeSucceeded
  lastFailureTime: '2025-06-06T19:42:55Z'
  message: Deployed
  nameCount: 41
  observedGeneration: 49
  phase: Deployed
  progressiveStatus:
    upgradingMonoVertexStatus:
      analysis:
        analysisRunName: numaplane-test-mvtx-40
        endTime: '2025-07-04T23:17:16Z'
        phase: Failed
        startTime: '2025-07-04T23:14:16Z'
      assessmentEndTime: '2025-07-04T23:18:16Z'
      assessmentResult: Failure
      assessmentStartTime: '2025-07-04T23:14:12Z'
      childStatus:
        conditions:
          - lastTransitionTime: '2025-07-04T23:09:15Z'
            message: Successful
            reason: Successful
            status: 'True'
            type: DaemonHealthy
          - lastTransitionTime: '2025-07-04T23:09:12Z'
            message: Successful
            reason: Successful
            status: 'True'
            type: Deployed
          - lastTransitionTime: '2025-07-04T23:09:12Z'
            message: All pods are healthy
            reason: Running
            status: 'True'
            type: PodsHealthy
        currentHash: b5ed03b6022fe499595e950384c5e126512bf869ec93446a076394efea72367f
        desiredReplicas: 2
        lastScaledAt: '2025-07-04T23:09:12Z'
        lastUpdated: '2025-07-04T23:09:22Z'
        observedGeneration: 1
        phase: Running
        readyReplicas: 2
        replicas: 2
        selector: >-
          app.kubernetes.io/component=mono-vertex,numaflow.numaproj.io/mono-vertex-name=numaplane-test-mvtx-40
        updateHash: b5ed03b6022fe499595e950384c5e126512bf869ec93446a076394efea72367f
        updatedReadyReplicas: 2
        updatedReplicas: 2
      failureReason: AnalysisRun numaplane-test-mvtx-40 is in phase Failed
      initializationComplete: true
      name: numaplane-test-mvtx-40
      originalScaleMinMax: '{"max":7,"min":3}'

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #810

### Modifications

This is a follow up to [this](https://github.com/numaproj/numaplane/pull/813) PR to add e2e testing. I noticed that we weren't testing for that ProgressiveSucceeded condition in any of our e2e tests. 

### Verification

N/A

### Backward incompatibilities

N/A

### CODE REVIEW

File: tests/e2e/pipeline.go [hunk 1]
```diff
@@ -634,6 +648,26 @@ func VerifyPipelineSuccess(pipelineRolloutName, promotedPipelineName, upgradingP
...
+		originalPipelineSpecVertices = append(originalPipelineSpecVertices, numaflowv1.AbstractVertex{Name: vertex.Name, Scale: vertex.Scale})
+	}
+	VerifyVerticesPodsRunning(Namespace, promotedPipelineName, originalPipelineSpecVertices, ComponentVertex)
+	upgradingPipelineSpecVerticesZero := []numaflowv1.AbstractVertex{}
+	for _, vertex := range upgradingPipelineSpec.Vertices {
+		upgradingPipelineSpecVerticesZero = append(upgradingPipelineSpecVerticesZero, numaflowv1.AbstractVertex{Name: vertex.Name, Scale: numaflowv1.Scale{Min: ptr.To(int32(0)), Max: ptr.To(int32(0))}})
+	}
+	VerifyVerticesPodsRunning(Namespace, upgradingPipelineName, upgradingPipelineSpecVerticesZero, ComponentVertex)
+
+	VerifyPipelineRolloutProgressiveCondition(pipelineRolloutName, metav1.ConditionFalse)
```
Comment (juliev0) [inline tests/e2e/pipeline.go:670]: moved this function to a central location and added the last check

**Review by afugazzotto — APPROVED** [review]
