### PR TITLE
fix: PDB label selector to match actual isbsvc pod names

### LINKED ISSUE #684: PDB needs to reference isbsvc
**Describe the bug**
PDB is referencing the name of the ISBServiceRollout rather than the isbsvc.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #684 

### Modifications

Previously, the isbsvc name we were using in the selector for the PDB was actually the name of the ISBServiceRollout. Originally, that worked well since the name of the isbsvc was always the same as the ISBServiceRollout.

Now we need to add a separate PDB for each ISBService, with pod selector fixed. 

Therefore, I've made sure we create one associated with our "promoted" isbsvc, but also one for our "upgrading" isbsvc.

The OwnerReference is on the isbsvc itself, so once the isbsvc gets deleted, the PDB is automatically deleted in turn.

Here is an example of one that's been generated:

```
jvogelman@macos-VF3V14X2QJ progressive % k get pdb -o yaml
apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2025-04-03T00:57:26Z"
    generation: 1
    name: my-isbsvc-197
    namespace: example-namespace
    ownerReferences:
    - apiVersion: numaflow.numaproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: InterStepBufferService
      name: my-isbsvc-197
      uid: 456cec42-f46a-4494-a006-81262f622ee6
    resourceVersion: "411846"
    uid: 806e0aa9-4172-4089-8613-7c1599df58a3
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: isbsvc
        numaflow.numaproj.io/isbsvc-name: my-isbsvc-197
  status:
    conditions:
    - lastTransitionTime: "2025-04-03T01:21:27Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 3
    desiredHealthy: 2
    disruptionsAllowed: 1
    expectedPods: 3
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
```

The label selector shown above matches these Pods:

```
jvogelman@macos-VF3V14X2QJ progressive % k get pod -l"app.kubernetes.io/component"=isbsvc -l"numaflow.numaproj.io/isbsvc-name"="my-isbsvc-197"
NAME                        READY   STATUS    RESTARTS   AGE
isbsvc-my-isbsvc-197-js-0   3/3     Running   0          22m
isbsvc-my-isbsvc-197-js-1   3/3     Running   0          22m
isbsvc-my-isbsvc-197-js-2   3/3     Running   0          23m
```

### Verification

Created ISBServiceRollout. Observed pdb created associated with isbsvc.
Updated ISBServiceRollout to cause a progressive upgrade. Observed pdb created with new isbsvc. Observed that previous pdb got deleted when previous isbsvc got deleted.

### Backward incompatibilities

N/A

### CODE REVIEW

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 1]
```diff
@@ -266,6 +266,9 @@ func (r *ISBServiceRolloutReconciler) reconcile(ctx context.Context, isbServiceR
 				if err = kubernetes.CreateResource(ctx, r.client, newISBServiceDef); err != nil {
 					return ctrl.Result{}, fmt.Errorf("error creating ISBService: %v", err)
 				}
+				if err = r.applyPodDisruptionBudget(ctx, newISBServiceDef); err != nil {
+					return ctrl.Result{}, fmt.Errorf("failed to apply PodDisruptionBudget for ISBService %s, err: %v", newISBServiceDef.GetName(), err)
+				}
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:271]: when we create "promoted" isbsvc, make sure we create PDB

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 2]
```diff
@@ -290,6 +293,9 @@ func (r *ISBServiceRolloutReconciler) reconcile(ctx context.Context, isbServiceR
 		if err != nil {
 			return ctrl.Result{}, fmt.Errorf("error getting ISBService: %v", err)
 		}
+		if err = r.applyPodDisruptionBudget(ctx, existingISBServiceDef); err != nil {
+			return ctrl.Result{}, fmt.Errorf("failed to apply PodDisruptionBudget for ISBService %s, UID=%s, err: %v", existingISBServiceDef.GetName(), existingISBServiceDef.GetUID(), err)
+		}
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:298]: when we already have an existing "promoted" isbsvc, make sure corresponding PDB exists and if not, create it (auto healing)

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 3]
```diff
@@ -626,9 +628,10 @@ func (r *ISBServiceRolloutReconciler) getPipelineListForChildISBSvc(ctx context.
 }
 
 // Apply pod disruption budget for the ISBService
-func (r *ISBServiceRolloutReconciler) applyPodDisruptionBudget(ctx context.Context, isbServiceRollout *apiv1.ISBServiceRollout) error {
-	pdb := kubernetes.NewPodDisruptionBudget(isbServiceRollout.Name, isbServiceRollout.Namespace, 1,
-		[]metav1.OwnerReference{*metav1.NewControllerRef(isbServiceRollout.GetObjectMeta(), apiv1.ISBServiceRolloutGroupVersionKind)},
+func (r *ISBServiceRolloutReconciler) applyPodDisruptionBudget(ctx context.Context, isbService *unstructured.Unstructured) error {
+	pdb := kubernetes.NewPodDisruptionBudget(isbService.GetName(), isbService.GetNamespace(), 1,
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:632]: now named by isbsvc

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 4]
```diff
@@ -626,9 +628,10 @@ func (r *ISBServiceRolloutReconciler) getPipelineListForChildISBSvc(ctx context.
...
+		[]metav1.OwnerReference{*metav1.NewControllerRef(&metav1.ObjectMeta{Name: isbService.GetName(), Namespace: isbService.GetNamespace(), UID: isbService.GetUID()},
+			numaflowv1.ISBGroupVersionKind)},
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:634]: owned by isbsvc

File: internal/controller/isbservicerollout/isbservicerollout_progressive.go [hunk 5]
```diff
@@ -126,3 +126,17 @@ func (r *ISBServiceRolloutReconciler) ProcessUpgradingChildPreUpgrade(
...
+	upgradingChildDef *unstructured.Unstructured,
+	c client.Client,
+) (bool, error) {
+
+	// need to make sure it has a PodDisruptionBudget associated with it, and owned by it
+	if err := r.applyPodDisruptionBudget(ctx, upgradingChildDef); err != nil {
+		return false, fmt.Errorf("failed to apply PodDisruptionBudget for ISBService %s, err: %v", upgradingChildDef.GetName(), err)
+	}
+	return false, nil
+}
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_progressive.go:142]: after we create "upgrading" isbsvc, create pdb

**Review by chandankumar4 — APPROVED** [review]
looks good, but commits need to be fixed
