### PR TITLE
fix: checking Pipeline conditions for PPND, plus don't pause failed pipelines

### LINKED ISSUE #230: Don't pause Failed pipelines
# Summary

Based on the contract with Numaflow, we will only try to pause pipelines that are not failed - those are the ones that are guaranteed to either pause or timeout. 

Agreement with Derek is that we can do an "Apply" directly on Pipelines which are not paused.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #230 

#### Modification 1: Don't pause "Failed" pipelines:

1. I don't pause pipelines if they're "Failed"
2. I can update the pipeline spec without waiting for a "Failed" pipeline to be "Paused"
3. I can update NumaflowController and ISBService specs if Pipelines are either "Paused" or "Failed"

##### Verification

1. unit test checks ISBService (same code is used for Numaflow Controller so presumably that is being verified at the same time)
2. manually tested this sequence: create bad pipeline which failed validation; attempted to update failed pipeline with a change which didn't fix the problem; updated failed pipeline by fixing the validation error
3. manually tested updating ISBServiceRO and NCRO while pipeline was failed 

#### Modification 2: Fix Pipeline Condition checking for PPND

Was accidentally checking the `PipelineRollout.Conditions` rather than `Pipeline.Conditions` when waiting for the Pipeline to be fully reconciled. 

##### Verification

I observed in the log that at the time we resumed the Pipeline all of the Child Conditions were in a healthy state. I also observed that the daemon was up and running.

#### Modification 3: e2e test

Have incorporated latest Numaflow release into e2e test.
Have increased suite timeout and added a comment in case we need to increase further in the future.
Have fixed the Makefile which was setting environment variable for the test related to bringing up a separate kubernetes environment, which we aren't using.

### CODE REVIEW

**Comment by juliev0** [comment]
I will do some manual testing of pipeline changes before marking this "Ready for Review"

File: Makefile [hunk 1]
```diff
@@ -115,7 +115,9 @@ test: codegen fmt vet envtest ## Run tests.
 
 .PHONY: test-e2e
 test-e2e: codegen fmt vet envtest ## Run e2e tests.
-	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" GOFLAGS="-count=1" go test -v ./tests/e2e/... 
+	GOFLAGS="-count=1" go test -v ./tests/e2e/...
```
Comment (juliev0) [inline Makefile:118]: don't think we need `KUBEBUILDER_ASSETS` which seems to set up a Kubernetes environment, which apparently sets up a Kubernetes environment. In the test we use our [existing](https://github.com/numaproj/numaplane/blob/main/tests/e2e/suite_test.go#L60) cluster.

File: internal/controller/isbservicerollout_controller_test.go [hunk 2]
```diff
@@ -324,6 +324,18 @@ func Test_reconcile_PPND(t *testing.T) {
...
+			newISBSvcSpec:          createDefaultISBServiceSpec("2.10.11"),
+			existingISBSvcDef:      createDefaultISBService("2.10.3", numaflowv1.ISBSvcPhaseRunning, true),
+			existingStatefulSetDef: createDefaultISBStatefulSet("2.10.3", true),
+			existingPipelinePhase:  numaflowv1.PipelinePhaseFailed,
+			expectedRolloutPhase:   apiv1.PhaseDeployed,
+			expectedConditionsSet: map[apiv1.ConditionType]metav1.ConditionStatus{
+				apiv1.ConditionChildResourceDeployed: metav1.ConditionTrue,
+			},
+			expectedISBSvcSpec: createDefaultISBServiceSpec("2.10.11"),
+		},
```
Comment (juliev0) [inline internal/controller/isbservicerollout_controller_test.go:338]: testing that ISBServiceRollout will ignore Failed pipelines for pausing

File: tests/e2e/common.go [hunk 3]
```diff
@@ -21,12 +21,13 @@ import (
...
-	cancel        context.CancelFunc
-	suiteTimeout  = 5 * time.Minute
-	testTimeout   = 2 * time.Minute
+	dynamicClient       dynamic.DynamicClient
+	testEnv             *envtest.Environment
+	ctx                 context.Context
+	cancel              context.CancelFunc
+	suiteTimeout        = 30 * time.Minute
+	testTimeout         = 2 * time.Minute
+	testPollingInterval = 1 * time.Second
```
Comment (juliev0) [inline tests/e2e/common.go:30]: I think it will be better to poll the K8S API once per second rather than the default once per 10ms just in case we ever do face a rate limiting issue

File: tests/manifests/default/controller_definitions.yaml [hunk 4]
```diff
@@ -318,7 +318,7 @@ controllerDefinitions:
             - controller
             env:
             - name: NUMAFLOW_IMAGE
-              value: quay.io/numaproj/numaflow:v1.3.0
```
Comment (juliev0) [inline tests/manifests/default/controller_definitions.yaml:321]: this diff is weird - note that I didn't remove 1.3.0

File: internal/controller/pause_requester.go [hunk 5]
```diff
@@ -49,12 +49,12 @@ func processChildObjectWithoutDataLoss(ctx context.Context, rollout client.Objec
 		if !pauseRequestUpdated && resourceNeedsUpdating {
 
 			// check if the pipelines are all paused
```
Comment (xdevxy) [inline internal/controller/pause_requester.go:51]: nit: update the comment accordingly

File: internal/controller/pipelinerollout_controller.go [hunk 6]
```diff
@@ -568,9 +570,12 @@ func pipelineIsUpdating(pipelineRollout *apiv1.PipelineRollout, newPipelineDef *
 	}
 
 	// note if Pipeline's children are still being updated
-	_, pipelineChildResourceReason := getPipelineChildResourceHealth(pipelineRollout.Status.Conditions)
+	unhealthyOrProgressing, _ := checkChildResources(existingPipelineStatus.Conditions, func(c metav1.Condition) bool {
+		// TODO: once we have "inProgressStrategy" we can just look for c.Status == metav1.ConditionFalse while inProgressStrategy==PPND
```
Comment (xdevxy) [inline internal/controller/pipelinerollout_controller.go:574]: is there a numaflow issue for this? can we add it here in the comment?

**Review by xdevxy — APPROVED** [review]

File: internal/controller/pipelinerollout_controller.go (hunk 6 above)
Comment (juliev0) [reply internal/controller/pipelinerollout_controller.go:574]: no longer a numaflow issue but rather just a numaplane issue which I can reference in the comment: https://github.com/numaproj/numaplane/issues/239
