### PR TITLE
fix: get just the live rollout resource when reconciling to avoid issues caused by getting cached status

### LINKED ISSUE #602: Check for possible race condition wrt failure to update RolloutStatus
**Describe the bug**

Currently, in the Success case, we promote the "upgrading" child and mark the old one as "recyclable" before we update the Rollout Status. 

So, there's a possibility that we could promote the "upgrading" child and mark the old one as "recyclable" and then attempt to update the `UpgradingChildStatus` as Successful but fail doing so. Next reconciliation, we would [exit](https://github.com/numaproj/numaplane/blob/v0.14.0/internal/controller/progressive/progressive.go#L125) the progressive strategy. Need to understand the consequences of that. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Mostly Fixes #602

### Modifications

Eventually, I'd like to have a local cache to store the Rollout Status, since we are the only ones writing to it. 

For now, however, I have updated the code to get the live Rollout every time to prevent cases like that identified by #602. 

I ended up doing this for the PipelineRollout, ISBServiceRollout, and MonoVertexRollout, since they are involved in the Progressive rollout case, in which we need to make sure we have the latest and greatest `Status` since we use that information that we previously wrote to inform what we do next.

Thus, I didn't end up changing NumaflowControllerRollout and NumaflowController because I don't believe we do anything like that for those. 

### Verification

I mostly no longer see the resource version conflict errors for these Rollouts in the CI logs. (I occasionally see one, but I think it's due to the test updating the Rollout in the middle of a reconciliation. That can still occur.)

### Backward incompatibilities

N/A

### CODE REVIEW

File: internal/controller/pipelinerollout/pipelinerollout_controller.go [hunk 1]
```diff
@@ -236,13 +232,13 @@ func (r *PipelineRolloutReconciler) processPipelineRollout(ctx context.Context,
...
+	r.recorder.Eventf(pipelineRollout, "Normal", "ReconcileSuccess", "Reconciliation successful")
+	numaLogger.Debug("reconciliation successful")
+
 	if requeueDelay > 0 {
 		return ctrl.Result{RequeueAfter: requeueDelay}, nil
 	}
 
-	r.recorder.Eventf(pipelineRollout, "Normal", "ReconcileSuccess", "Reconciliation successful")
-	numaLogger.Debug("reconciliation successful")
-
```
Comment (juliev0) [inline internal/controller/pipelinerollout/pipelinerollout_controller.go:245]: this wasn't getting logged before in the case of requeue

**Review by afugazzotto — APPROVED** [review]
