### PR TITLE
fix: (E2E) Remove Document fn call and refactor

### LINKED ISSUE #500: Improve error messaging in e2e test
# Summary

When there's a failure in a given test, it can be hard to figure out why it failed. 

**Issue 1: forgetting to call `document()`:**
Right now we have the `document()` statements in there which give us some idea where we are in the test. When we forget to add them prior to every test, we can't tell where it failed. Perhaps there's some structural change that would make it so we always have them? Here's an idea: maybe we never call `Eventually` or `Consistently` directly: instead we call some function which calls those, and it also takes a string argument which we print. 

**Issue 2: panics:**
I also know that once when an Eventually() test panicked in its function block, the panic wasn't displayed.

**Issue 3:**
This one is not as critical but is it possible to print more information when an `Eventually` or `Consistently` test fails and contains multiple test conditions in it? Maybe we can start to figure out possible strategies.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by chandankumar4**
Fixes #500 

### Modifications

- Removing Documentation fn call and created a wrapper method for `Eventually()` and `Consistently()` for printing the test case name as well while run.

### CODE REVIEW

File: tests/e2e/common.go [hunk 1]
```diff
@@ -571,3 +553,13 @@ func setupOutputDir() {
...
+
+func CheckEventually(testData string, actualOrCtx interface{}) AsyncAssertion {
+	By(testData)
+	return Eventually(actualOrCtx, testTimeout, testPollingInterval)
+}
+
+func CheckConsistently(testData string, actualOrCtx interface{}) AsyncAssertion {
+	By(testData)
+	return Consistently(actualOrCtx, testTimeout, testPollingInterval)
+}
```
Comment (juliev0) [inline tests/e2e/common.go:565]: I want to get this merged sooner than later so you don't have merge conflicts, but one thing I'm thinking is that it would be great to be able to optionally specify the timeout or the polling interval if we need to.

Comment (juliev0) [reply tests/e2e/common.go:565]: oh wait, cool, I see you were able to do that by calling `CheckEventually(...).WithTimeout(...)`, right?

Comment (juliev0) [reply tests/e2e/common.go:565]: maybe we can just comment these functions to clarify that you can override the default timeout and default poll interval that way?

**Review by juliev0 — APPROVED** [review]

**Comment by juliev0** [comment]
sorry there are merge conflicts! I've approved, so feel free to fix the conflicts, add the comments I mentioned [here](https://github.com/numaproj/numaplane/pull/579#discussion_r1962871979), and then merge yourself

File: Makefile [hunk 2]
```diff
@@ -128,10 +128,8 @@ test: codegen fmt vet envtest ## Run unit tests.
 
 test-functional-e2e:
 test-ppnd-e2e:
-test-%: codegen fmt vet envtest ## Run e2e tests. Note we may need to increase the timeout in the future.
-	GOFLAGS="-count=1" go test -timeout 35m -v ./tests/e2e/$* 
-
-
+test-%: envtest ## Run e2e tests. Note we may need to increase the timeout in the future.
+	GOFLAGS="-count=1" ginkgo -v ./tests/e2e/$*
```
Comment (juliev0) [inline Makefile:132]: is there a "timeout" flag for ginkgo call? 

Note that the comment above still refers to a timeout. Also, I should've mentioned it, but in a recent [PR](https://github.com/numaproj/numaplane/pull/570/files), I noticed that we were timing out in 3 different places (here in the Makefile, in the Github action, and in the ginkgo code itself), so I decided to only leave this one and remove the other 2. 

If we can't do it here, then perhaps we should add one of the other ones back.

Comment (chandankumar4) [reply Makefile]: Added timeout here with `ginkgo run`

Comment (juliev0) [reply Makefile]: nice
