### PR TITLE
fix: codegen and upgrade k8s componenets version

### LINKED ISSUE #329: fix codegen for numaplane kube clients
**Describe the bug**
According to Derek, the [update-codegen.sh](https://github.com/numaproj/numaplane/blob/main/hack/update-codegen.sh) script which was added to Numaflow, similar to Numaplane, isn't generating new code. He fixed it in [this](https://github.com/numaproj/numaflow/pull/2127/files#diff-149dfe7bb29d1191dceae3a52915e750e64b7f87257a5fb309c29d3056e2a95d) PR (among other changes) as part of updating to K8S client version 1.31. He says this works for >= 1.30 and not 1.29.

I see in our go.mod file it indicates we are using k8s client 1.29.2, as the k8s.io modules are at 0.29.2 (module at 0.29.2 = k8s client at 1.29.2).

Either we revert the change that was made to update-codegen.sh [here](https://github.com/numaproj/numaplane/commit/86c5de7dbbf494cf1ed4d25bf06e97bd59b1a322) (which results in a  permission issue that can be worked around by adding a temporary "sudo") or we can upgrade to > 1.29 like numaflow did.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by chandankumar4**
Fixes #329 

### Verification

Verified in local kind cluster

```bash
$ k get po -A
NAMESPACE            NAME                                            READY   STATUS    RESTARTS      AGE
example-namespace    isbsvc-my-isbsvc-js-0                           3/3     Running   0             14m
example-namespace    isbsvc-my-isbsvc-js-1                           3/3     Running   0             14m
example-namespace    isbsvc-my-isbsvc-js-2                           3/3     Running   0             14m
example-namespace    my-pipeline-0-cat-0-a03ec                       2/2     Running   0             8m48s
example-namespace    my-pipeline-0-daemon-598654654f-76kvh           1/1     Running   0             8m48s
example-namespace    my-pipeline-0-in-0-poexr                        1/1     Running   0             8m48s
example-namespace    my-pipeline-0-out-0-ve5mv                       1/1     Running   0             8m48s
example-namespace    numaflow-controller-7675ff47fd-xbh2t            1/1     Running   0             15m
example-namespace    numaflow-dex-server-67877dc869-q64c8            1/1     Running   0             15m
example-namespace    numaflow-server-65f46c5db7-pbs8c                1/1     Running   0             15m
numaplane-system     numaplane-controller-manager-5967ccf485-rrgt6   1/1     Running   0             15m
```

### CODE REVIEW

File: internal/controller/isbservicerollout_controller.go [hunk 1]
```diff
@@ -615,9 +615,9 @@ func (r *ISBServiceRolloutReconciler) SetupWithManager(mgr ctrl.Manager) error {
 		Group:   common.NumaflowAPIGroup,
 		Version: common.NumaflowAPIVersion,
 	})
-	if err := controller.Watch(source.Kind(mgr.GetCache(), isbServiceUns),
-		handler.EnqueueRequestForOwner(mgr.GetScheme(), mgr.GetRESTMapper(), &apiv1.ISBServiceRollout{}, handler.OnlyControllerOwner()),
-		predicate.ResourceVersionChangedPredicate{}); err != nil {
+	if err := controller.Watch(source.Kind(mgr.GetCache(), isbServiceUns,
+		handler.TypedEnqueueRequestForOwner[*unstructured.Unstructured](mgr.GetScheme(), mgr.GetRESTMapper(),
+			&apiv1.ISBServiceRollout{}, handler.OnlyControllerOwner()))); err != nil {
```
Comment (chandankumar4) [inline internal/controller/isbservicerollout_controller.go:620]: I'm trying to add `predicate.ResourceVersionChangedPredicate{}` according to new definition of watch

File: internal/controller/monovertexrollout_controller.go [hunk 2]
```diff
@@ -336,10 +337,10 @@ func (r *MonoVertexRolloutReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 		Version: common.NumaflowAPIVersion,
 	})
-	if err := controller.Watch(source.Kind(mgr.GetCache(), monoVertexUns),
-		handler.EnqueueRequestForOwner(mgr.GetScheme(), mgr.GetRESTMapper(), &apiv1.MonoVertexRollout{}, handler.OnlyControllerOwner()),
-		predicate.ResourceVersionChangedPredicate{}); err != nil {
-		return err
+	if err := controller.Watch(source.Kind(mgr.GetCache(), monoVertexUns,
+		handler.TypedEnqueueRequestForOwner[*unstructured.Unstructured](mgr.GetScheme(), mgr.GetRESTMapper(),
+			&apiv1.MonoVertexRollout{}, handler.OnlyControllerOwner()), predicate.TypedResourceVersionChangedPredicate[*unstructured.Unstructured]{})); err != nil {
+		return fmt.Errorf("failed to watch MonoVertices: %w", err)
```
Comment (juliev0) [inline internal/controller/monovertexrollout_controller.go:343]: Good job figuring out how to make this work for `*Unstructured` type - that's too bad that this stuff wasn't backward compatible as is

File: internal/controller/pipelinerollout_controller.go [hunk 3]
```diff
@@ -96,7 +96,7 @@ type PipelineRolloutReconciler struct {
 	// queue contains the list of PipelineRollouts that currently need to be reconciled
 	// both PipelineRolloutReconciler.Reconcile() and other Rollout reconcilers can add PipelineRollouts to this queue to be processed as needed
 	// a set of Workers is used to process this queue
-	queue workqueue.RateLimitingInterface
+	queue workqueue.TypedRateLimitingInterface[interface{}]
```
Comment (juliev0) [inline internal/controller/pipelinerollout_controller.go:99]: nice job figuring out this one as well. This task was definitely not trivial :)

**Review by juliev0 — APPROVED** [review]
