### PR TITLE
fix: Handle deletions of promoted child gracefully

### LINKED ISSUE #739: Handle use case in which user deletes a promoted or upgrading pipeline during progressive rollout
# Summary

We saw a use case in which user deleted their Promoted pipeline after the Upgrading one was failed. The upgrade was still in progress, and this confused it. A new "promoted" Pipeline was created in that case. The "promotedPipelineStatus" showed the new pipeline's name but no other information which caused this failure in PipelineRollout:
```
Failed to reconcile PipelineRollout unable to restore scale values for the promoted pipeline vertices because the rollout does not have promotedChildStatus set
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by juliev0**
Fixes #739 

### Modifications

If a user deletes a Promoted child while in the middle of Progressive upgrade (could be prior to Assessment or after it's failed), then in addition to the Promoted child being recreated, any Upgrading children are deleted and then `upgradeInProgress` field is set back to "".

### Verification

For each of the 3 rollouts, tested prior to Assessment and after Assessment failure. Then I also, just in case, did a subsequent Progressive upgrade just to make sure that worked fine too. 

### Backward incompatibilities

N/A

### CODE REVIEW

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 1]
```diff
@@ -252,22 +252,17 @@ func (r *ISBServiceRolloutReconciler) reconcile(ctx context.Context, isbServiceR
...
-				if err = kubernetes.CreateResource(ctx, r.client, newISBServiceDef); err != nil {
-					return ctrl.Result{}, fmt.Errorf("error creating ISBService: %v", err)
-				}
-				if err = r.applyPodDisruptionBudget(ctx, newISBServiceDef); err != nil {
-					return ctrl.Result{}, fmt.Errorf("failed to apply PodDisruptionBudget for ISBService %s, err: %v", newISBServiceDef.GetName(), err)
-				}
-				if err := ctlrcommon.CreateRidersForNewChild(ctx, r, isbServiceRollout, newISBServiceDef, r.client); err != nil {
-					return ctrl.Result{}, fmt.Errorf("error creating riders: %s", err)
+
+				if err = r.createPromotedISBService(ctx, isbServiceRollout, newISBServiceDef); err != nil {
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:264]: for each rollout, I moved the logic into a new function

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 2]
```diff
@@ -401,6 +396,7 @@ func (r *ISBServiceRolloutReconciler) processExistingISBService(ctx context.Cont
 		if err != nil {
 			if apierrors.IsNotFound(err) {
 				numaLogger.WithValues("isbsvcDefinition", *newISBServiceDef).Warn("InterstepBufferService not found.")
+				return 0, nil
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:399]: we should've been returning here (otherwise, it will cause panic later)

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 3]
```diff
@@ -789,6 +785,31 @@ func (r *ISBServiceRolloutReconciler) needsUpdate(old, new *apiv1.ISBServiceRoll
...
+	// if user somehow has no Promoted ISBService and is in the middle of Progressive, this isn't right - user may have deleted the Promoted one
+	// if this happens, we need to stop the Progressive upgrade and remove any Upgrading children
+	inProgressStrategy := r.inProgressStrategyMgr.GetStrategy(ctx, isbServiceRollout)
+
+	if inProgressStrategy == apiv1.UpgradeStrategyProgressive {
+		r.inProgressStrategyMgr.UnsetStrategy(ctx, isbServiceRollout)
+		if err := progressive.Discontinue(ctx, isbServiceRollout, r, r.client); err != nil {
+			return err
+		}
+	}
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:808]: this last `if` condition is what I added to each rollout

File: internal/controller/isbservicerollout/isbservicerollout_controller.go [hunk 4]
```diff
@@ -789,6 +785,31 @@ func (r *ISBServiceRolloutReconciler) needsUpdate(old, new *apiv1.ISBServiceRoll
...
+	return nil
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller.go:809]: this is the block I added for each rollout

File: internal/controller/isbservicerollout/isbservicerollout_controller_test.go [hunk 5]
```diff
@@ -404,12 +404,44 @@ func Test_reconcile_isbservicerollout_Progressive(t *testing.T) {
...
+		UpgradingChildStatus: apiv1.UpgradingChildStatus{
+			Name:                   ctlrcommon.DefaultTestISBSvcRolloutName + "-1",
+			AssessmentStartTime:    &metav1.Time{Time: time.Now().Add(-1 * time.Minute)},
+			AssessmentEndTime:      &metav1.Time{Time: time.Now().Add(-30 * time.Second)},
+			AssessmentResult:       apiv1.AssessmentResultSuccess,
+			InitializationComplete: true,
+		},
+	}
+	failedUpgradingISBServiceStatus := successfulUpgradingISBServiceStatus.DeepCopy()
+	failedUpgradingISBServiceStatus.UpgradingChildStatus.AssessmentResult = apiv1.AssessmentResultFailure
```
Comment (juliev0) [inline internal/controller/isbservicerollout/isbservicerollout_controller_test.go:437]: As part of adding tests, I decided to refactor a bit (finding some definitions that were common and creating variables out of them)

**Review by afugazzotto — APPROVED** [review]
