### PR TITLE
fix: pod artifacts were not populating properly. Fixes #301

### LINKED ISSUE #301: e2e Debuggability - Pods directory doesn't seem to have all of the Pods
**Describe the bug**

Both in the CI and on my local machine, I have seen not all Pods exist in `tests/e2e/resources/pipelinerollouts/pods` for some reason.

Locally, I just ran the test and failed it [here](https://github.com/numaproj/numaplane/blob/main/tests/e2e/functional_test.go#L398) (this line is not commented out in my branch). And my `tests/e2e/resources/pipelinerollouts/pods` directory is empty.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by dpadhiar**
Fixes #301

### Modifications

We were previously not collecting `job` pod logs before. This was causing issues when creating logs for both PipelineRollout and MonoVertexRollout pods. Therefore, we have now included them which has fixed the issue.

### Verification

Running `make test-e2e` locally with both failing and successful tests.

Running on Github CI with a failing test to view artifacts output properly - https://github.com/numaproj/numaplane/pull/303/commits/9106f8fe6302b73ff4c09158b0ef78e97d2ccbbf

### CODE REVIEW

File: tests/e2e/common.go [hunk 1]
```diff
@@ -193,7 +192,7 @@ func watchPods() {
 						fileName = filepath.Join(ResourceChangesISBServiceOutputPath, "pods", strings.Join([]string{pod.Name, ".yaml"}, ""))
 					case "mono-vertex", "mono-vertex-daemon":
 						fileName = filepath.Join(ResourceChangesMonoVertexOutputPath, "pods", strings.Join([]string{pod.Name, ".yaml"}, ""))
-					case "daemon", "vertex":
+					case "daemon", "vertex", "job":
 						fileName = filepath.Join(ResourceChangesPipelineOutputPath, "pods", strings.Join([]string{pod.Name, ".yaml"}, ""))
```
Comment (juliev0) [inline tests/e2e/common.go:196]: how about having a default case if it doesn't match any of the above that does a `continue`?

**Review by juliev0 — APPROVED** [review]

**Review by xdevxy — APPROVED** [review]
