### PR TITLE
fix: refactor unstructured_util and reduce k8s api call

### LINKED ISSUE #344: Refactor unstructured_util and reduce the number of call to k8s API
# Summary

What change needs making?
- Remove redundant code from unstructured_util
- MonoVertex Watch should be Unstructured
- Prevent calls to REST API when getting Status of child
- Set DynamicClient at once, instead of generating it in each API call
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by chandankumar4**
Fixes #344

### Modifications
- MonoVertex Watch should be Unstructured
- Remove redundant code from unstructured_util
- Prevent calls to REST API when getting Status of child
- Set DynamicClient at once, instead of generating it in each API call

### Verification

Verified in local kind cluster

### CODE REVIEW

File: internal/controller/isbservicerollout_controller.go [hunk 1]
```diff
@@ -230,8 +226,8 @@ func (r *ISBServiceRolloutReconciler) reconcile(ctx context.Context, isbServiceR
 
 	newISBServiceDef := &kubernetes.GenericObject{
 		TypeMeta: metav1.TypeMeta{
-			Kind:       "InterStepBufferService",
-			APIVersion: "numaflow.numaproj.io/v1alpha1",
+			Kind:       common.NumaflowISBServiceKind,
+			APIVersion: common.NumaflowAPIGroup + "/" + common.NumaflowAPIVersion,
```
Comment (juliev0) [inline internal/controller/isbservicerollout_controller.go:230]: nice

File: internal/controller/pipelinerollout_controller.go [hunk 2]
```diff
@@ -559,23 +555,24 @@ func pipelineObservedGenerationCurrent(generation int64, observedGeneration int6
...
+	// Only fetch the latest pipeline object while deleting the pipeline object, i.e. when pipelineRollout.DeletionTimestamp.IsZero() is false
+	if existingPipelineDef == nil {
+		pipelineDef, err := r.makeRunningPipelineDefinition(ctx, pipelineRollout)
+		if err != nil {
+			return err
+		}
+		livePipelineDef, err := kubernetes.GetLiveResource(ctx, pipelineDef, "pipelines")
+		if err != nil {
+			if apierrors.IsNotFound(err) {
+				numaLogger.WithValues("pipelineDefinition", *pipelineDef).Warn("Pipeline not found. Unable to process status during this reconciliation.")
```
Comment (juliev0) [inline internal/controller/pipelinerollout_controller.go:570]: should we return if this happens? otherwise, `livePipelineDef` would be nil, right?

File: internal/util/kubernetes/unstructured_util.go [hunk 3]
```diff
@@ -400,6 +247,7 @@ func GetResource(ctx context.Context, c client.Client, gvk schema.GroupVersionKi
 	return UnstructuredToObject(unstructuredObj)
 }
 
+// UpdateResource updates the resource in the kubernetes cluster
```
Comment (juliev0) [inline internal/util/kubernetes/unstructured_util.go:250]: thanks for all the housekeeping!

**Review by juliev0 — APPROVED** [review]
